---
- name: Install repo
  yum:
    name: "{{ newrelic_repo_rpm }}"
    state: present

- name: Install newrelic agent
  yum:
    name: "{{ newrelic_packages }}"
    state: "present"

- name: Configure newrelic agent
  template:
    src: newrelic.ini.j2
    dest: /etc/php.d/newrelic.ini
